test yml
Signed-off-by: Igor Duquia Giumelli <igor.giumelli@zup.com.br>

diff --git a/.github/workflows/automated_tests_appium_android.yml b/.github/workflows/automated_tests_appium_android.yml
--- a/.github/workflows/automated_tests_appium_android.yml
+++ b/.github/workflows/automated_tests_appium_android.yml
@@ -54,6 +54,15 @@ jobs:
       - name: Print branch info
         run: git branch
 
+      - name: script testing
+        run: |
+          case 4.4 in
+          4.4) echo"Google Nexus 5" ;;
+          6) echo "Google Nexus 6" ;;
+          8) echo "Google Pixel 2" ;;
+          11) echo "Google Pixel 4" ;;
+          *) echo "Invalid option!" && exit 1 ;;
+
       # Cache Gradle dependencies
       - name: Setup Gradle Dependencies Cache
         uses: actions/cache@v2
@@ -230,20 +239,17 @@ jobs:
 
         # BrowseStack Android devices: https://www.browserstack.com/list-of-browsers-and-platforms/app_automate
       - name: Returns Android device to be used based on Android version
-        uses: actions/github-script@v4
         id: sets-android-device
         env:
           ANDROID_VERSION: ${{ matrix.android-version }}
-        with:
-          script: |
-            case $ANDROID_VERSION in
-            4.4) echo ::set-output name=result::"Google Nexus 5" ;;
-            6) echo ::set-output name=result::"Google Nexus 6" ;;
-            8) echo ::set-output name=result::"Google Pixel 2" ;;
-            11) echo ::set-output name=result::"Google Pixel 4" ;;
-            *) echo "Invalid option!" && exit 1 ;;
-            esac
-          result-encoding: string
+        run: |
+          case $ANDROID_VERSION in
+          4.4) echo ::set-output name=result::"Google Nexus 5" ;;
+          6) echo ::set-output name=result::"Google Nexus 6" ;;
+          8) echo ::set-output name=result::"Google Pixel 2" ;;
+          11) echo ::set-output name=result::"Google Pixel 4" ;;
+          *) echo "Invalid option!" && exit 1 ;;
+
 
       - name: Run the Appium test suite
         uses: actions/github-script@v4
