test ci scripts
Signed-off-by: Igor Duquia Giumelli <igor.giumelli@zup.com.br>

diff --git a/.github/workflows/automated_tests_appium_android.yml b/.github/workflows/automated_tests_appium_android.yml
--- a/.github/workflows/automated_tests_appium_android.yml
+++ b/.github/workflows/automated_tests_appium_android.yml
@@ -16,16 +16,29 @@
 
 name: Beagle Appium Android tests
 
-on:
-  workflow_dispatch:
-  workflow_run:
-    workflows: [ "Beagle Appium tests trigger" ]
-    types:
-      - completed
+  #on:
+  #  workflow_dispatch:
+  #  workflow_run:
+  #    workflows: [ "Beagle Appium tests trigger" ]
+  #    types:
+  #      - completed
+
+  # Bellow configuration is for testing this workflow without merging to main
+  on:
+    push:
+      branches:
+        - main
+      paths:
+        - '.github/**'
+    pull_request:
+      branches:
+        - main
+      paths:
+        - '.github/**'
 
 jobs:
   bff_config_job:
-    name: BFF configuration job
+    name: BFF server configuration
     runs-on: ubuntu-20.04
     timeout-minutes: 10
     env:
@@ -74,11 +87,10 @@ jobs:
           CLUSTER: ${{ env.BEAGLE_CORE_AWS_AWS_CLUSTER_NAME }}
           NAMESPACE: ${{ env.BEAGLE_CORE_AWS_AWS_CLUSTER_NAMESPACE }}
 
-  appium_tests:
-    needs: bff_config_job
-    name: Tests job
+  apk_config_in_browserstack_job:
+    name: APK compilation and upload in BrowserStack
     runs-on: macos-latest
-    timeout-minutes: 90
+    timeout-minutes: 10
     steps:
       - uses: actions/checkout@v2
         with:
@@ -112,12 +124,99 @@ jobs:
           bash ./appium/app-android/gradlew assembleDebug -p appium/app-android
           # sed -i --expression "s@$BFF_URL@http://10.0.2.2:8080@g" $BEAGLE_CONFIG_FILE
 
-      - name: Upload .apk file in BrowserStack and run the Appium test suite
+      - name: Upload the .apk file in BrowserStack and save the returned id into a file
         env:
           BFF_URL: ${{ env.BEAGLE_CORE_TEST_BEAGLE_TESTS_BFF_URL }}
           BROWSERSTACK_USER: ${{ env.BEAGLE_CORE_TEST_BEAGLE_TESTS_BROWSERSTACK_USER }}
           BROWSERSTACK_KEY: ${{ env.BEAGLE_CORE_TEST_BEAGLE_TESTS_BROWSERSTACK_KEY }}
-        run: bash fastlane/automatedTests/appium/android/browserstack/setup_apk_in_browserstack_and_run_android_tests.sh
+        run: bash fastlane/automatedTests/appium/android/browserstack/setup_apk_in_browserstack_and_export_id_in_file.sh
+
+      - name: Upload BrowserStack id file
+        uses: actions/upload-artifact@v1
+        with:
+          name: browserstack-app-id
+          path: browserstack_app_id.txt
+
+  appium_tests:
+    needs: bff_config_job
+    name: Tests
+    runs-on: macos-latest
+    timeout-minutes: 90
+    strategy:
+      fail-fast: false
+      matrix:
+        android-version: [ 4.4, 6, 8, 11 ]
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          ref: ${{ github.event.workflow_run.head_branch }}
+          submodules: 'true'
+
+      - run: git branch
+
+      - name: Setup JDK (11)
+        uses: actions/setup-java@v2
+        with:
+          distribution: 'adopt'
+          java-version: '11'
+
+      - name: Read secrets from AWS Secrets Manager into environment variables
+        uses: abhilash1in/aws-secrets-manager-action@v1.0.1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
+          secrets: |
+            beagle/core/*
+          parse-json: true
+
+      - name: Sets var BROWSERSTACK_UPLOAD_ID with BrowserStack id file
+        uses: actions/download-artifact@v1
+        with:
+          name: browserstack-app-id
+        run: echo "BROWSERSTACK_UPLOAD_ID=$(<browserstack_app_id.txt)" >> $GITHUB_ENV
+
+        # BrowseStack Android devices: https://www.browserstack.com/list-of-browsers-and-platforms/app_automate
+      - name: Returns Android device to be used based on Android version
+        uses: actions/github-script@v4
+        id: sets-android-device
+        env:
+          ANDROID_VERSION: ${{ matrix.android-version }}
+        with:
+          script: |
+            case $ANDROID_VERSION in
+            4.4) return "Google Nexus 5" ;;
+            6) return "Google Nexus 6" ;;
+            8) return "Google Pixel 2" ;;
+            11) return "Google Nexus 4" ;;
+            *) echo "Invalid option!" && exit 1 ;;
+            esac
+          result-encoding: string
+
+      - name: Run the Appium test suite
+        uses: actions/github-script@v4
+        env:
+          DEVICE_NAME: ${{steps.sets-android-device.outputs.result}}
+          ANDROID_VERSION: ${{ matrix.android-version }}
+          BFF_URL: ${{ env.BEAGLE_CORE_TEST_BEAGLE_TESTS_BFF_URL }}
+          BROWSERSTACK_USER: ${{ env.BEAGLE_CORE_TEST_BEAGLE_TESTS_BROWSERSTACK_USER }}
+          BROWSERSTACK_KEY: ${{ env.BEAGLE_CORE_TEST_BEAGLE_TESTS_BROWSERSTACK_KEY }}
+        with:
+          script: |
+            echo "Running Appium tests..."
+            if ./appium/project/gradlew --build-cache -p appium/project cucumber \
+            -Dplatform="android" \
+            -Dplatform_version="$ANDROID_VERSION" \
+            -Ddevice_name="$DEVICE_NAME" \
+            -Dbrowserstack_user="$BROWSERSTACK_USER" \
+            -Dbrowserstack_key="$BROWSERSTACK_KEY" \
+            -Dapp_file="$BROWSERSTACK_UPLOAD_ID" \
+            -Dbff_base_url="$BFF_URL"; then
+            echo "Gradle task succeeded" >&2
+            else
+            echo "Gradle task failed" >&2
+            exit 1
+            fi
 
       - name: Expose failed test screenshot files
         if: failure()
