ci tests
Signed-off-by: Igor Duquia Giumelli <igor.giumelli@zup.com.br>

diff --git a/.github/workflows/automated_tests_appium_ios.yml b/.github/workflows/automated_tests_appium_ios.yml
--- a/.github/workflows/automated_tests_appium_ios.yml
+++ b/.github/workflows/automated_tests_appium_ios.yml
@@ -29,81 +29,85 @@ jobs:
     runs-on: macos-latest
     timeout-minutes: 90
     steps:
-      - uses: actions/checkout@v2
-        with:
-          ref: ${{ github.event.workflow_run.head_branch }}
-          submodules: 'true'
-
-      - name: Update submodules
-        run: git submodule update --init --recursive --remote
-
-      - name: Print branch info
-        run: git branch
-
-      - name: Setup JDK (11)
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'adopt'
-          java-version: '11'
-
-      ##################################################################################################
-      # Caching - Start
-      ##################################################################################################
-      - name: Cache fastlane dependences
-        uses: actions/cache@v2
-        env:
-          fastlane-cache-key: fastlane-cache-test
-          fastlane-path: ~/.gem
-        with:
-          path: ${{ env.fastlane-path }}
-          key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('Gemfile.lock') }}
-      ##################################################################################################
-      # Caching - end
-      ##################################################################################################
-
-      - name: Install Fastlane
-        run: bundle config set path '~/.gem' && bundle install
-
-      - name: Build and start the BFF server
-        run: bash fastlane/automatedTests/start_test_backend.sh
-
-      - name: Config and run Appium server
-        run: bash fastlane/automatedTests/appium/config_and_run_appium_server.sh
-
-      - name: Build app-ios project to generate the app file
-        run: |
-          set -e
-          xcodebuild -showsdks
-          xcodebuild -project appium/app-ios/AppiumApp/AppiumApp.xcodeproj -scheme AppiumApp -destination 'platform=iOS Simulator,name=iPhone 11' -quiet
+      - name: prints simulators
+        run: xcrun simctl list runtimes
 
 
-      ##################################################################################################
-      # Emulator config - start
-      ##################################################################################################
-
-      - name: Prepare iOS 13.5 simulator
-        run: |
-          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
-          # We use simulator 13.5 for the tests. It uses Xcode 11.5, according to https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md. 
-          # Since GitHub Actions uses another Xcode version, we need to make a symlink inside Xcode, pointing to the iOS version we want.
-          # More details: https://github.com/actions/virtual-environments/issues/551#issuecomment-637344435
-          sudo ln -s /Applications/Xcode_11.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 13.5.simruntime
-          xcrun simctl create TestiPhoneX com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-5 > ~/deviceIdTemp.txt
-          DEVICEUUID=`cat ~/deviceIdTemp.txt`
-          xcrun simctl boot $DEVICEUUID
-          sleep 30
-
-      ##################################################################################################
-      # Emulator config - end
-      ##################################################################################################
-
-      - name: Run the tests
-        run: bash fastlane/automatedTests/appium/ios/run_appium_ios_tests.sh
-
-      - name: Expose failed test screenshot files
-        if: failure()
-        uses: actions/upload-artifact@v2
-        with:
-          name: failed_tests_screenshots
-          path: appium/project/build/screenshots/
+#      - uses: actions/checkout@v2
+#        with:
+#          ref: ${{ github.event.workflow_run.head_branch }}
+#          submodules: 'true'
+#
+#      - name: Update submodules
+#        run: git submodule update --init --recursive --remote
+#
+#      - name: Print branch info
+#        run: git branch
+#
+#      - name: Setup JDK (11)
+#        uses: actions/setup-java@v2
+#        with:
+#          distribution: 'adopt'
+#          java-version: '11'
+#
+#      ##################################################################################################
+#      # Caching - Start
+#      ##################################################################################################
+#      - name: Cache fastlane dependences
+#        uses: actions/cache@v2
+#        env:
+#          fastlane-cache-key: fastlane-cache-test
+#          fastlane-path: ~/.gem
+#        with:
+#          path: ${{ env.fastlane-path }}
+#          key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('Gemfile.lock') }}
+#      ##################################################################################################
+#      # Caching - end
+#      ##################################################################################################
+#
+#      - name: Install Fastlane
+#        run: bundle config set path '~/.gem' && bundle install
+#
+#      - name: Build and start the BFF server
+#        run: bash fastlane/automatedTests/start_test_backend.sh
+#
+#      - name: Config and run Appium server
+#        run: bash fastlane/automatedTests/appium/config_and_run_appium_server.sh
+#
+#      - name: Build app-ios project to generate the app file
+#        run: |
+#          set -e
+#          xcodebuild -showsdks
+#          xcodebuild -project appium/app-ios/AppiumApp/AppiumApp.xcodeproj -scheme AppiumApp -destination 'platform=iOS Simulator,name=iPhone 11' -quiet
+#
+#
+#      ##################################################################################################
+#      # Emulator config - start
+#      ##################################################################################################
+#
+#      - name: Prepare iOS 13.5 simulator
+#        run: |
+#          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
+#          # We use simulator 13.5 for the tests. It uses Xcode 11.5, according to https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md.
+#          # Since GitHub Actions uses another Xcode version, we need to make a symlink inside Xcode, pointing to the iOS version we want.
+#          # More details: https://github.com/actions/virtual-environments/issues/551#issuecomment-637344435
+#          sudo ln -s /Applications/Xcode_11.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 13.5.simruntime
+#          xcrun simctl create TestiPhoneX com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-5 > ~/deviceIdTemp.txt
+#          DEVICEUUID=`cat ~/deviceIdTemp.txt`
+#          xcrun simctl boot $DEVICEUUID
+#          sleep 30
+#
+#      ##################################################################################################
+#      # Emulator config - end
+#      ##################################################################################################
+#
+#      - name: Run the tests
+#        run: bash fastlane/automatedTests/appium/ios/run_appium_ios_tests.sh
+#
+#      - name: Expose failed test screenshot files
+#        if: failure()
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: failed_tests_screenshots
+#          path: appium/project/build/screenshots/
 
