ci tests
Signed-off-by: Igor Duquia Giumelli <igor.giumelli@zup.com.br>

diff --git a/.github/workflows/automated_tests_appium_ios.yml b/.github/workflows/automated_tests_appium_ios.yml
--- a/.github/workflows/automated_tests_appium_ios.yml
+++ b/.github/workflows/automated_tests_appium_ios.yml
@@ -24,90 +24,189 @@ on:
       - completed
 
 jobs:
+  compile_bff_project:
+    name: Compile BFF project
+    runs-on: ubuntu-20.04
+    timeout-minutes: 10
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          ref: ${{ github.event.workflow_run.head_branch }}
+          submodules: 'true'
+
+      - name: Update submodules
+        run: git submodule update --init --recursive --remote
+
+      - name: Print branch info
+        run: git branch
+
+      # Cache Gradle dependencies
+      - name: Setup Gradle Dependencies Cache
+        uses: actions/cache@v2
+        with:
+          path: ~/.gradle/caches
+          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
+
+      # Cache Gradle Wrapper
+      - name: Setup Gradle Wrapper Cache
+        uses: actions/cache@v2
+        with:
+          path: ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
+
+      - name: Setup JDK (11)
+        uses: actions/setup-java@v2
+        with:
+          distribution: 'adopt'
+          java-version: '11'
+
+      - name: Generate the BFF jar file
+        with:
+          path: bff-server
+        run: |
+          if ./gradlew bootJar
+          then
+            echo "Gradle task succeeded" >&2
+          else
+            echo "Gradle task failed" >&2
+            exit 1
+          fi
+
+      - name: Upload the BFF jar file
+        uses: actions/upload-artifact@v2
+        with:
+          name: bff-jar-file
+          path: bff-server/bff/build/libs/bff.jar
+
+
   appium_tests:
     name: Tests job
     runs-on: macos-latest
+    needs: compile_bff_project
     timeout-minutes: 90
+    strategy:
+      fail-fast: false
+      matrix:
+        ios-version: [ 10, 12.4, 14.4 ]
     steps:
-      - name: prints simulators
-        run: xcrun simctl list runtimes
+      - uses: actions/checkout@v2
+        with:
+          ref: ${{ github.event.workflow_run.head_branch }}
+          submodules: 'true'
+
+      - name: Update submodules
+        run: git submodule update --init --recursive --remote
+
+      - name: Print branch info
+        run: git branch
+
+      - name: Download the BFF jar file
+        uses: actions/download-artifact@v2
+        with:
+          name: bff-jar-file
+
+      - name: Start the BFF server
+        run: nohup java -jar bff.jar 2>&1 &
+
+      - name: Config and run the Appium server
+        run: bash fastlane/automatedTests/appium/config_and_run_appium_server.sh
+
+      - name: Returns the iOS device to be used based on the iOS version
+        id: sets-ios-device
+        env:
+          IOS_VERSION: ${{ matrix.ios-version }}
+        run: |
+          case IOS_VERSION in
+          10) echo ::set-output name=result::"iPhone 7" ;;
+          12.4) echo ::set-output name=result::"iPhone 11" ;;
+          14.4) echo ::set-output name=result::"iPhone 11" ;;
+          *) echo "Invalid option!" && exit 1 ;;
+          esac
+
+      # TODO: TRY TO MAKE THIS STEP IN ONE JOB (multiple dests or generic): https://mokacoding.com/blog/xcodebuild-destination-options/
+      - name: Build the app-ios project to generate the app file
+        env:
+          DEVICE_NAME: ${{steps.sets-ios-device.outputs.result}}
+          IOS_VERSION: ${{ matrix.ios-version }}
+        run: |
+          set -e
+          xcodebuild -showsdks
+          xcodebuild -project appium/app-ios/AppiumApp/AppiumApp.xcodeproj -scheme AppiumApp -destination 'platform=iOS Simulator,name=$DEVICE_NAME' -quiet
+
+      - name: Config the simulator according to the iOS version
+        env:
+          IOS_VERSION: ${{ matrix.ios-version }}
+        run: |
+          case IOS_VERSION in
+          10)
+            xcversion simulators --install='iOS 10.3.1'
+            xcode-select --switch/Applications/Xcode_10.3.app/Contents/Developer
+            xcrun simctl create TestiPhoneX com.apple.CoreSimulator.SimDeviceType.iPhone-7 com.apple.CoreSimulator.SimRuntime.iOS-10-3 > ~/deviceIdTemp.txt
+            DEVICEUUID=`cat ~/deviceIdTemp.txt`
+            xcrun simctl boot $DEVICEUUID
+            sleep 30
+            ;;
+          12.4)
+            echo "TODO" && exit 1
+            ;;
+          14.4)
+            echo "TODO" && exit 1
+            ;;
+          *)
+            echo "Invalid option!" && exit 1
+            ;;
+          esac
 
 
-#      - uses: actions/checkout@v2
-#        with:
-#          ref: ${{ github.event.workflow_run.head_branch }}
-#          submodules: 'true'
-#
-#      - name: Update submodules
-#        run: git submodule update --init --recursive --remote
-#
-#      - name: Print branch info
-#        run: git branch
-#
-#      - name: Setup JDK (11)
-#        uses: actions/setup-java@v2
-#        with:
-#          distribution: 'adopt'
-#          java-version: '11'
-#
-#      ##################################################################################################
-#      # Caching - Start
-#      ##################################################################################################
-#      - name: Cache fastlane dependences
-#        uses: actions/cache@v2
-#        env:
-#          fastlane-cache-key: fastlane-cache-test
-#          fastlane-path: ~/.gem
-#        with:
-#          path: ${{ env.fastlane-path }}
-#          key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('Gemfile.lock') }}
-#      ##################################################################################################
-#      # Caching - end
-#      ##################################################################################################
-#
-#      - name: Install Fastlane
-#        run: bundle config set path '~/.gem' && bundle install
-#
-#      - name: Build and start the BFF server
-#        run: bash fastlane/automatedTests/start_test_backend.sh
-#
-#      - name: Config and run Appium server
-#        run: bash fastlane/automatedTests/appium/config_and_run_appium_server.sh
-#
-#      - name: Build app-ios project to generate the app file
-#        run: |
-#          set -e
-#          xcodebuild -showsdks
-#          xcodebuild -project appium/app-ios/AppiumApp/AppiumApp.xcodeproj -scheme AppiumApp -destination 'platform=iOS Simulator,name=iPhone 11' -quiet
-#
-#
-#      ##################################################################################################
-#      # Emulator config - start
-#      ##################################################################################################
-#
-#      - name: Prepare iOS 13.5 simulator
-#        run: |
-#          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
-#          # We use simulator 13.5 for the tests. It uses Xcode 11.5, according to https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md.
-#          # Since GitHub Actions uses another Xcode version, we need to make a symlink inside Xcode, pointing to the iOS version we want.
-#          # More details: https://github.com/actions/virtual-environments/issues/551#issuecomment-637344435
-#          sudo ln -s /Applications/Xcode_11.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 13.5.simruntime
-#          xcrun simctl create TestiPhoneX com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-5 > ~/deviceIdTemp.txt
-#          DEVICEUUID=`cat ~/deviceIdTemp.txt`
-#          xcrun simctl boot $DEVICEUUID
-#          sleep 30
-#
-#      ##################################################################################################
-#      # Emulator config - end
-#      ##################################################################################################
-#
-#      - name: Run the tests
-#        run: bash fastlane/automatedTests/appium/ios/run_appium_ios_tests.sh
-#
-#      - name: Expose failed test screenshot files
-#        if: failure()
-#        uses: actions/upload-artifact@v2
-#        with:
-#          name: failed_tests_screenshots
-#          path: appium/project/build/screenshots/
+      ##################################################################################################
+      # Emulator config - start
+      ##################################################################################################
+
+      #      - name: Prepare iOS 13.5 simulator
+      #        run: |
+      #          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
+      #          # We use simulator 13.5 for the tests. It uses Xcode 11.5, according to https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md.
+      #          # Since GitHub Actions uses another Xcode version, we need to make a symlink inside Xcode, pointing to the iOS version we want.
+      #          # More details: https://github.com/actions/virtual-environments/issues/551#issuecomment-637344435
+      #          sudo ln -s /Applications/Xcode_11.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 13.5.simruntime
+      #          xcrun simctl create TestiPhoneX com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-5 > ~/deviceIdTemp.txt
+      #          DEVICEUUID=`cat ~/deviceIdTemp.txt`
+      #          xcrun simctl boot $DEVICEUUID
+      #          sleep 30
+
+      ##################################################################################################
+      # Emulator config - end
+      ##################################################################################################
+
+      #      - name: Run the tests
+      #        run: bash fastlane/automatedTests/appium/ios/run_appium_ios_tests.sh
+
+      - name: Run the Appium test suite
+        with:
+          path: bff-server
+        env:
+          DEVICE_NAME: ${{steps.sets-ios-device.outputs.result}}
+          IOS_VERSION: ${{ matrix.ios-version }}
+        run: |
+          APP_FILE=$(find ~/Library/Developer/Xcode/DerivedData -name AppiumApp.app | grep Build/Products/Debug-iphonesimulator/AppiumApp.app)
+          echo ".app file found at: $APP_FILE"
+          echo "Running Appium tests on device $DEVICE_NAME with iOS $IOS_VERSION..."
+          chmod +x $APPIUM_PROJECT_DIR/gradlew
+          if ./appium/project/gradlew --build-cache -p appium/project cucumber \
+          -Dplatform="ios" \
+          -Dplatform_version="$IOS_VERSION" \
+          -Ddevice_name="$DEVICE_NAME" \
+          -Dapp_file="$APP_FILE"; then
+            echo "Gradle task succeeded" >&2
+           else
+            echo "Gradle task failed" >&2
+            exit 1
+           fi
+
+      - name: Expose failed test screenshot files
+        if: failure()
+        uses: actions/upload-artifact@v2
+        with:
+          name: failed_tests_screenshots
+          path: appium/project/build/screenshots/
 
